# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testMonkey_eve' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for testMonkey_eve

end

target 'testMonkey_eveDylib' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'ZFPlayer'
  pod 'ZFDownload', '~> 1.0.2'
  pod 'GDataXMLNode2', '~> 2.0.1'
pod 'CocoaAsyncSocket', '~> 7.6.2' 
 # Pods for testMonkey_eveDylib 
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CLANG_ENABLE_OBJC_WEAK'] ||= 'NO'
        end
    end
end

