# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testMonkey_eve' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for testMonkey_eve

end

target 'testMonkey_eveDylib' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'ZFPlayer'
  # Pods for testMonkey_eveDylib

end
